spring.application.name=foody-delivery-backend
server.port=${PORT:8080}

# Database Configurations (H2 Embedded - armazena localmente em arquivo ./data/foody_delivery.mv.db)
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/foody_delivery;AUTO_SERVER=TRUE}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 Console (Para inspecionar o banco se desejar via navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Security / JWT Custom Properties
api.security.jwt.secret=${JWT_SECRET:65F+lflcf4OI5Au5df7G/zw7aL6wQrdSw8njGJS/H8qJfrlnJ8k3wV6qXTfWAGyYtW2oyTlzVM5lRQsB5H+YCg==}
api.security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
